/* =====================================================================
 * idt.c - Interrupt Descriptor Table + 8259 PIC management
 *
 * This file builds the table that tells the CPU "when interrupt
 * number X fires, jump to this assembly stub". It also remaps the
 * legacy 8259 PIC so hardware IRQs (which default to vectors 0-15,
 * clashing with CPU exceptions) land on vectors 32-47 instead. This
 * remap is a mandatory step for any real x86 kernel.
 * ===================================================================== */

#include "../include/types.h"
#include "../include/io.h"
#include "../include/idt.h"
#include "../kernel/lib/kstring.h"

struct idt_entry {
    uint16_t base_low;
    uint16_t sel;
    uint8_t  always0;
    uint8_t  flags;
    uint16_t base_high;
} __attribute__((packed));

struct idt_ptr {
    uint16_t limit;
    uint32_t base;
} __attribute__((packed));

#define IDT_ENTRIES 256
static struct idt_entry idt[IDT_ENTRIES];
static struct idt_ptr   ip;

extern void idt_flush(uint32_t idt_ptr_addr);

/* 32 exception entry points, generated by macros in boot/isr.S */
extern void isr0(); extern void isr1(); extern void isr2(); extern void isr3();
extern void isr4(); extern void isr5(); extern void isr6(); extern void isr7();
extern void isr8(); extern void isr9(); extern void isr10(); extern void isr11();
extern void isr12(); extern void isr13(); extern void isr14(); extern void isr15();
extern void isr16(); extern void isr17(); extern void isr18(); extern void isr19();
extern void isr20(); extern void isr21(); extern void isr22(); extern void isr23();
extern void isr24(); extern void isr25(); extern void isr26(); extern void isr27();
extern void isr28(); extern void isr29(); extern void isr30(); extern void isr31();

/* 16 hardware IRQ entry points from boot/isr.S (remapped to 32-47) */
extern void irq0(); extern void irq1(); extern void irq2(); extern void irq3();
extern void irq4(); extern void irq5(); extern void irq6(); extern void irq7();
extern void irq8(); extern void irq9(); extern void irq10(); extern void irq11();
extern void irq12(); extern void irq13(); extern void irq14(); extern void irq15();

static isr_handler_t irq_handlers[16];

static void idt_set_gate(uint8_t num, uint32_t base, uint16_t sel, uint8_t flags) {
    idt[num].base_low  = base & 0xFFFF;
    idt[num].base_high = (base >> 16) & 0xFFFF;
    idt[num].sel        = sel;
    idt[num].always0    = 0;
    idt[num].flags      = flags;
}

/* ---- Remap the 8259 PIC so IRQs land on vectors 32-47 ---- */
static void pic_remap(void) {
    uint8_t mask1 = inb(0x21);
    uint8_t mask2 = inb(0xA1);

    outb(0x20, 0x11); io_wait();   /* start initialization (ICW1) - master */
    outb(0xA0, 0x11); io_wait();   /* start initialization (ICW1) - slave  */

    outb(0x21, 0x20); io_wait();   /* master PIC vector offset: 32 */
    outb(0xA1, 0x28); io_wait();   /* slave  PIC vector offset: 40 */

    outb(0x21, 0x04); io_wait();   /* tell master there's a slave at IRQ2 */
    outb(0xA1, 0x02); io_wait();   /* tell slave its cascade identity     */

    outb(0x21, 0x01); io_wait();   /* 8086 mode */
    outb(0xA1, 0x01); io_wait();

    outb(0x21, mask1);             /* restore saved interrupt masks */
    outb(0xA1, mask2);
}

void pic_send_eoi(uint8_t irq) {
    if (irq >= 8)
        outb(0xA0, 0x20);   /* End-Of-Interrupt to the slave PIC  */
    outb(0x20, 0x20);       /* End-Of-Interrupt to the master PIC */
}

void irq_install_handler(int irq, isr_handler_t handler) {
    irq_handlers[irq] = handler;
}

void idt_init(void) {
    ip.limit = sizeof(struct idt_entry) * IDT_ENTRIES - 1;
    ip.base  = (uint32_t)&idt;

    memset(&idt, 0, sizeof(struct idt_entry) * IDT_ENTRIES);

    pic_remap();

    idt_set_gate(0, (uint32_t)isr0, 0x08, 0x8E);
    idt_set_gate(1, (uint32_t)isr1, 0x08, 0x8E);
    idt_set_gate(2, (uint32_t)isr2, 0x08, 0x8E);
    idt_set_gate(3, (uint32_t)isr3, 0x08, 0x8E);
    idt_set_gate(4, (uint32_t)isr4, 0x08, 0x8E);
    idt_set_gate(5, (uint32_t)isr5, 0x08, 0x8E);
    idt_set_gate(6, (uint32_t)isr6, 0x08, 0x8E);
    idt_set_gate(7, (uint32_t)isr7, 0x08, 0x8E);
    idt_set_gate(8, (uint32_t)isr8, 0x08, 0x8E);
    idt_set_gate(9, (uint32_t)isr9, 0x08, 0x8E);
    idt_set_gate(10, (uint32_t)isr10, 0x08, 0x8E);
    idt_set_gate(11, (uint32_t)isr11, 0x08, 0x8E);
    idt_set_gate(12, (uint32_t)isr12, 0x08, 0x8E);
    idt_set_gate(13, (uint32_t)isr13, 0x08, 0x8E);
    idt_set_gate(14, (uint32_t)isr14, 0x08, 0x8E);
    idt_set_gate(15, (uint32_t)isr15, 0x08, 0x8E);
    idt_set_gate(16, (uint32_t)isr16, 0x08, 0x8E);
    idt_set_gate(17, (uint32_t)isr17, 0x08, 0x8E);
    idt_set_gate(18, (uint32_t)isr18, 0x08, 0x8E);
    idt_set_gate(19, (uint32_t)isr19, 0x08, 0x8E);
    idt_set_gate(20, (uint32_t)isr20, 0x08, 0x8E);
    idt_set_gate(21, (uint32_t)isr21, 0x08, 0x8E);
    idt_set_gate(22, (uint32_t)isr22, 0x08, 0x8E);
    idt_set_gate(23, (uint32_t)isr23, 0x08, 0x8E);
    idt_set_gate(24, (uint32_t)isr24, 0x08, 0x8E);
    idt_set_gate(25, (uint32_t)isr25, 0x08, 0x8E);
    idt_set_gate(26, (uint32_t)isr26, 0x08, 0x8E);
    idt_set_gate(27, (uint32_t)isr27, 0x08, 0x8E);
    idt_set_gate(28, (uint32_t)isr28, 0x08, 0x8E);
    idt_set_gate(29, (uint32_t)isr29, 0x08, 0x8E);
    idt_set_gate(30, (uint32_t)isr30, 0x08, 0x8E);
    idt_set_gate(31, (uint32_t)isr31, 0x08, 0x8E);

    idt_set_gate(32, (uint32_t)irq0, 0x08, 0x8E);
    idt_set_gate(33, (uint32_t)irq1, 0x08, 0x8E);
    idt_set_gate(34, (uint32_t)irq2, 0x08, 0x8E);
    idt_set_gate(35, (uint32_t)irq3, 0x08, 0x8E);
    idt_set_gate(36, (uint32_t)irq4, 0x08, 0x8E);
    idt_set_gate(37, (uint32_t)irq5, 0x08, 0x8E);
    idt_set_gate(38, (uint32_t)irq6, 0x08, 0x8E);
    idt_set_gate(39, (uint32_t)irq7, 0x08, 0x8E);
    idt_set_gate(40, (uint32_t)irq8, 0x08, 0x8E);
    idt_set_gate(41, (uint32_t)irq9, 0x08, 0x8E);
    idt_set_gate(42, (uint32_t)irq10, 0x08, 0x8E);
    idt_set_gate(43, (uint32_t)irq11, 0x08, 0x8E);
    idt_set_gate(44, (uint32_t)irq12, 0x08, 0x8E);
    idt_set_gate(45, (uint32_t)irq13, 0x08, 0x8E);
    idt_set_gate(46, (uint32_t)irq14, 0x08, 0x8E);
    idt_set_gate(47, (uint32_t)irq15, 0x08, 0x8E);

    idt_flush((uint32_t)&ip);
    sti();
}

/* Common C-side handler for CPU exceptions (0-31). For now we just
   swallow them; a real OS would show a panic screen / handle page
   faults here. */
void isr_handler(registers_t *regs) {
    (void)regs;
}

/* Common C-side handler for hardware IRQs (32-47): dispatch to
   whichever driver registered itself for this IRQ number. */
void irq_handler(registers_t *regs) {
    int irq = regs->int_no - 32;
    if (irq_handlers[irq] != 0) {
        irq_handlers[irq](regs);
    }
    pic_send_eoi(irq);
}
